server:
  port: 8888
spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/emrekazanci/Java7configyml.git"
          default-label: main
          skip-ssl-validation: true
          username: emrekazanci
          password: ${GIT_JAVA7_PASSWORD}