server:
  port: 9090
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/FacebookAuthDB
    username: postgres
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

my-application:
  jwt:
    secret-key: "sT*&r4b1EDra45fEXO7A#rAZaJ$Y-CrA2#L=9lGox!*R@=ReSpUsWOk6T-qeflmi"
    secret-key-env: ${SECRET_KEY}