server:
  port: 9092

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: post-service
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root
  data:
    mongodb:
      host: localhost
      port: 27017
      database: FacebookDB
      username: Java7User
      password: root

my-application:
  jwt:
    secret-key: "sT*&r4b1EDra45fEXO7A#rAZaJ$Y-CrA2#L=9lGox!*R@=ReSpUsWOk6T-qeflmi"